# CLI formulae installed directly on this Mac, plus Universal Ctags for Vim.
brew "awscli"
brew "ccusage"
brew "deno"
brew "fish"
brew "gh"
brew "git"
brew "neovim"
brew "nodebrew"
brew "openjdk"
brew "pnpm"
brew "python-yq"
brew "rbenv"
brew "ripgrep"
brew "spectral-cli"
brew "the_silver_searcher"
brew "universal-ctags"
brew "yarn"
